### ISSUE TITLE
ShadowsocksR代理方式 - vimcaw的个人博客

### ISSUE THREAD

**Issue by vimcaw** [vimcaw/blog#2]
https://vimcaw.github.io/blog/2017/08/13/ShadowsocksR%E4%BB%A3%E7%90%86%E6%96%B9%E5%BC%8F/

**Comment by wywncdx** [comment]
写的太棒了，解答了我的疑惑！网上教程只是讲了下搞代理的流程，最后能访问google就完了。。我非常疑惑‘pac’和'代理规则'这两项设置，总感觉像是冲突了似的。。直到看到你这篇文章，解惑了！希望这篇文章能让更多人看到！

**Comment by wongtou** [comment]
这是我想要理解的，谢谢

**Comment by MeolaZhang** [comment]
感谢博主！看了你的解释明白很多，今天刚接触这些，急需补补基础知识。
